// config/rolePermissions.js

const roles = {
	superadmin: [
		'create-client',
		'view-client',
		'update-client',
		'delete-client',
		'create-user',
		'view-user',
		'update-user',
		'delete-user',
		'delete-expense',
		'view-logs',
		'create-employee',
		'view-employee',
		'create-expense',
		'view-expense',
		'create-invoice',
		'view-invoice',
		'create-service',
		'view-service',
		'view-tax',
		'view-vat',
		'create-vat',	],
	admin: [
		'create-client',
		'view-client',
		'update-client',
		'delete-client',
		'create-user',
		'view-user',
		'update-user',
		'delete-user',
		'create-employee',
		'view-employee',
		'create-expense',
		'view-expense',
		'create-invoice',
		'view-invoice',
		'create-service',
		'view-service',
		'view-tax',
		'view-vat',
		'create-vat',
		// Other admin-specific permissions
	],
	clientAdmin: [
		'create-client',
		'view-client',
		'update-client',
		'create-employee',
		'view-employee',
		'create-expense',
		'view-expense',
		'create-invoice',
		'view-invoice',
		'create-service',
		'view-service',
		'view-tax',
		'view-vat',
		'create-vat',
	],
	employee: [
		'create-client',
		'view-client',
		'create-employee',
		'view-employee',
		'create-expense',
		'view-expense',
		'create-invoice',
		'view-invoice',
		'create-service',
		'view-service',
		'view-tax',
		'view-vat',
		'create-vat'
		// Other employee-specific permissions
	]
};

module.exports = roles;
